name: "Changelog"
on:
  issues:
    types: [closed,reopened]
  push:
    branches:
      - '[1-9]+.[0-9]+.x'
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]         
  workflow_dispatch:
jobs:
  release_notes:
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ“ Update release notes draft"
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}